## Samples
samples: 'sample names' # separated by spaces, no comma

## Step names
step1: s2B # sam to bam conversion
step2: vC # variant calling - freebayes

## Directories
# Base data dir
base_dir: /home/data/

# Change to location of all raw .sam files
raw_data_dir: /home/data/raw/

# Path to reference genome
ref_genome: /home/data/ref_genome.fa

# Path to input bam files
bam_files: /home/data/s2B/
