## Samples
samples: 'sample1 sample2 sample3 sample4
          sample5 sample6 sample7 sample8'

## Step names
step1: s2B # sam to bam conversion
step2: vC # variant calling - freebayes
step3: ciVCF # convert and index vcf

## Directories
# Base data dir
base_dir: /home/base/

# Change to location of all raw .sam files
raw_data_dir: /home/base/raw/

# Path to reference genome
ref_genome: /home/base/raw/ref_seq.unpadded.fasta

# Path to input bam files
bam_files: /home/base/raw/s2B/
